# Generated by Django 4.1.6 on 2023-02-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='strategy_id',
            new_name='strategy',
        ),
    ]
