# Generated by Django 4.1.6 on 2023-02-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_alter_trade_id_alter_trade_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
