# Generated by Django 4.1.6 on 2023-02-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_pnldata_capture_time_pnldata_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
