# Generated by Django 4.1.6 on 2023-02-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_alter_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
